files:
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/map.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/localization.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/planning.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/perception.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/control.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/vehicle.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/system.yaml }
  - { path: $(find-pkg-share autoware_launch_lomby)/config/system/system_diagnostic_monitor/sensing.yaml }

units:
  - path: /autoware/modes/stop
    type: ok

  - path: /autoware/modes/autonomous
    type: and
    list:
      - { type: link, link: /autoware/map }
      - { type: link, link: /autoware/localization }
      - { type: link, link: /autoware/planning }
      - { type: link, link: /autoware/perception }
      - { type: link, link: /autoware/control }
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/sensing }

  - path: /autoware/modes/local
    type: and
    list:
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/control/local }

  - path: /autoware/modes/remote
    type: and
    list:
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/control/remote }

  - path: /autoware/modes/emergency_stop
    type: and
    list:
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }

  - path: /autoware/modes/comfortable_stop
    type: and
    list:
      - { type: link, link: /autoware/map }
      - { type: link, link: /autoware/localization }
      - { type: link, link: /autoware/planning }
      - { type: link, link: /autoware/perception }
      - { type: link, link: /autoware/control }
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/sensing }

  - path: /autoware/modes/pull_over
    type: and
    list:
      - { type: link, link: /autoware/map }
      - { type: link, link: /autoware/localization }
      - { type: link, link: /autoware/planning }
      - { type: link, link: /autoware/perception }
      - { type: link, link: /autoware/control }
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/sensing }

  - path: /autoware/debug/tools
    type: and
    list:
      - { type: link, link: /autoware/system/service_log_checker }
