/**:
  ros__parameters:
    tolerance: 0.4
    voxel_leaf_size: 0.05
    min_points_number_per_voxel: 1
    min_cluster_size: 2
    max_cluster_size: 3000
    use_height: false
    input_frame: "base_link"

    #<<<This part is not being used for obstacle detection?!>>>
    # low height crop box filter param
    max_x: 30.0
    min_x: -30.0
    max_y: 30.0
    min_y: -30.0
    max_z: 2.0
    min_z: -10.0

